package sidecar

import (
    "crypto/sha256"
    "encoding/hex"
    "encoding/json"
    "fmt"
    "sort"
    "strings"
    "github.com/kakon77777-commits/isql-origin-go/wire"
)
type BridgePlan struct{Schema string `json:"schema"`;SourceProfile string `json:"source_profile"`;TargetProfile string `json:"target_profile"`;SourceArtifactKind *string `json:"source_artifact_kind"`;TargetArtifactKind *string `json:"target_artifact_kind"`;TransitionRef string `json:"transition_ref"`;FidelityClass int `json:"fidelity_class"`;Preserved []string `json:"preserved_invariants"`;Lost []string `json:"lost_invariants"`;ValidatorRef string `json:"validator_ref"`;AuthorityRef string `json:"authority_ref"`;ProvenanceRef string `json:"provenance_ref"`;TemporalRef *string `json:"temporal_ref"`}
type NativeEndpoint struct{Profile string `json:"profile"`;ArtifactKind string `json:"artifact_kind"`;NativeVersion int `json:"native_version"`;NativeSHA256 string `json:"native_sha256"`;NativeBytes int `json:"native_bytes"`}
type BridgeInvariantResult struct{InvariantRef string `json:"invariant_ref"`;Comparator string `json:"comparator"`;Passed bool `json:"passed"`;SourceObservableSHA256 string `json:"source_observable_sha256"`;TargetObservableSHA256 string `json:"target_observable_sha256"`;SourceObservableBytes int `json:"source_observable_bytes"`;TargetObservableBytes int `json:"target_observable_bytes"`;Distance *int `json:"distance"`;Tolerance *int `json:"tolerance"`}
type BridgeReceipt struct{Schema string `json:"schema"`;Canonical bool `json:"canonical"`;Status string `json:"status"`;Execute bool `json:"execute"`;ConversionPerformed bool `json:"conversion_performed"`;Source NativeEndpoint `json:"source"`;Target NativeEndpoint `json:"target"`;TransitionRef string `json:"transition_ref"`;FidelityClass int `json:"fidelity_class"`;Preserved []string `json:"preserved_invariants"`;Lost []string `json:"lost_invariants"`;ValidationResults []BridgeInvariantResult `json:"validation_results"`;ValidatorRef string `json:"validator_ref"`;AuthorityRef string `json:"authority_ref"`;ProvenanceRef string `json:"provenance_ref"`;TemporalRef *string `json:"temporal_ref"`;OutputDigest string `json:"output_digest"`;Errors []string `json:"errors"`}
func parseRefText(s string)(wire.Ref,error){var a,b uint64;if _,err:=fmt.Sscanf(s,"%d:%d",&a,&b);err!=nil{return wire.Ref{},fmt.Errorf("REF_INVALID:%s",s)};return wire.Ref{BundleSlot:a,LocalID:b},nil}
func validateRefList(xs []string)error{refs:=make([]wire.Ref,len(xs));seen:=map[wire.Ref]bool{};for i,s:=range xs{r,e:=parseRefText(s);if e!=nil{return e};if seen[r]{return fmt.Errorf("REF_LIST_DUPLICATE")};seen[r]=true;refs[i]=r};if !sort.SliceIsSorted(refs,func(i,j int)bool{if refs[i].BundleSlot!=refs[j].BundleSlot{return refs[i].BundleSlot<refs[j].BundleSlot};return refs[i].LocalID<refs[j].LocalID}){return fmt.Errorf("REF_LIST_NOT_CANONICAL")};return nil}
func validSHA(s string)bool{if len(s)!=64{return false};_,e:=hex.DecodeString(s);return e==nil}
func ParseBridgePlan(data []byte)(BridgePlan,error){var p BridgePlan;if err:=json.Unmarshal(data,&p);err!=nil{return p,err};if p.Schema!="isql-origin-bridge-plan/v0.5"{return p,fmt.Errorf("P4_BRIDGE_PLAN_SCHEMA_INVALID")};if p.SourceProfile==""||p.TargetProfile==""{return p,fmt.Errorf("P4_BRIDGE_PROFILE_INVALID")};if p.SourceProfile==p.TargetProfile{return p,fmt.Errorf("P4_BRIDGE_SAME_PROFILE_FORBIDDEN")};if p.FidelityClass<0||p.FidelityClass>4{return p,fmt.Errorf("P4_BRIDGE_FIDELITY_INVALID")};for _,s:=range []string{p.TransitionRef,p.ValidatorRef,p.AuthorityRef,p.ProvenanceRef}{if _,e:=parseRefText(s);e!=nil{return p,e}};if p.TemporalRef!=nil{if _,e:=parseRefText(*p.TemporalRef);e!=nil{return p,e}};if e:=validateRefList(p.Preserved);e!=nil{return p,e};if e:=validateRefList(p.Lost);e!=nil{return p,e};seen:=map[string]bool{};for _,x:=range p.Preserved{seen[x]=true};for _,x:=range p.Lost{if seen[x]{return p,fmt.Errorf("P4_BRIDGE_INVARIANT_OVERLAP")}};return p,nil}
func ParseBridgeReceipt(data []byte)(BridgeReceipt,error){var r BridgeReceipt;if err:=json.Unmarshal(data,&r);err!=nil{return r,err};if r.Schema!="isql-origin-bridge-receipt/v0.5"{return r,fmt.Errorf("P4_RECEIPT_SCHEMA_INVALID")};if r.Execute||r.ConversionPerformed{return r,fmt.Errorf("P4_RECEIPT_BOUNDARY_INVALID")};if r.Status!="VERIFIED"&&r.Status!="REJECTED"{return r,fmt.Errorf("P4_RECEIPT_STATUS_INVALID")};if r.Source.Profile==""||r.Target.Profile==""||r.Source.Profile==r.Target.Profile{return r,fmt.Errorf("P4_RECEIPT_PROFILE_INVALID")};if r.FidelityClass<0||r.FidelityClass>4{return r,fmt.Errorf("P4_BRIDGE_FIDELITY_INVALID")};if !validSHA(r.Source.NativeSHA256)||!validSHA(r.Target.NativeSHA256)||!validSHA(r.OutputDigest){return r,fmt.Errorf("P4_RECEIPT_DIGEST_INVALID")};if r.OutputDigest!=r.Target.NativeSHA256{return r,fmt.Errorf("P4_RECEIPT_OUTPUT_DIGEST_MISMATCH")};if e:=validateRefList(r.Preserved);e!=nil{return r,e};if e:=validateRefList(r.Lost);e!=nil{return r,e};seen:=map[string]bool{};for _,x:=range r.Preserved{seen[x]=true};for _,x:=range r.Lost{if seen[x]{return r,fmt.Errorf("P4_BRIDGE_INVARIANT_OVERLAP")}};if len(r.ValidationResults)!=len(r.Preserved){return r,fmt.Errorf("P4_RECEIPT_VALIDATION_RESULT_SET_MISMATCH")};allPass:=true;for i,res:=range r.ValidationResults{if res.InvariantRef!=r.Preserved[i]{return r,fmt.Errorf("P4_RECEIPT_VALIDATION_RESULT_SET_MISMATCH")};if !validSHA(res.SourceObservableSHA256)||!validSHA(res.TargetObservableSHA256){return r,fmt.Errorf("P4_RECEIPT_RESULT_INVALID")};if res.SourceObservableBytes<0||res.TargetObservableBytes<0{return r,fmt.Errorf("P4_RECEIPT_RESULT_INVALID")};if !res.Passed{allPass=false}};if r.Status=="VERIFIED"&&(!allPass||len(r.Errors)!=0){return r,fmt.Errorf("P4_RECEIPT_STATUS_INCONSISTENT")};if r.Status=="REJECTED"&&allPass&&len(r.Errors)==0{return r,fmt.Errorf("P4_RECEIPT_STATUS_INCONSISTENT")};return r,nil}
func VerifyBridgeReceiptBinding(r BridgeReceipt,source,target []byte)[]string{errs:=[]string{};sh:=sha256.Sum256(source);th:=sha256.Sum256(target);ss:=hex.EncodeToString(sh[:]);ts:=hex.EncodeToString(th[:]);if ss!=strings.ToLower(r.Source.NativeSHA256){errs=append(errs,"P4_RECEIPT_SOURCE_DIGEST_MISMATCH")};if ts!=strings.ToLower(r.Target.NativeSHA256){errs=append(errs,"P4_RECEIPT_TARGET_DIGEST_MISMATCH")};if len(source)!=r.Source.NativeBytes{errs=append(errs,"P4_RECEIPT_SOURCE_LENGTH_MISMATCH")};if len(target)!=r.Target.NativeBytes{errs=append(errs,"P4_RECEIPT_TARGET_LENGTH_MISMATCH")};if ts!=strings.ToLower(r.OutputDigest){errs=append(errs,"P4_RECEIPT_OUTPUT_DIGEST_MISMATCH")};return errs}
