package sections

import "github.com/kakon77777-commits/isql-origin-go/wire"

type SemanticChart struct { Chart,ChartType wire.Ref; Version uint64; Domain,CoordinateSchema,Payload,Authority,Provenance wire.Ref; Flags uint64 }
type Transition struct { Transition,SourceChart,TargetChart,Transformer wire.Ref; FidelityClass uint64; Deterministic,Reversible bool; Bound wire.Ref; Preserved,Lost []wire.Ref; Validator,Authority,Provenance wire.Ref }
type Operator struct { Operator,DomainType,CodomainType,Signature,Guard wire.Ref; Capabilities,Effects,AuthorityRequirements,InvariantObligations []wire.Ref; Executor *wire.Ref; ResourceBound,Provenance wire.Ref }
type AuthorityRecord struct { Authority,Subject,Issuer wire.Ref; Grants,Denies []wire.Ref; Scope wire.Ref; Validity,Evidence,Signature *wire.Ref }

func DecodeSemanticCharts(d []byte)([]SemanticChart,error){c:=cur{d:d};n,e:=c.u();if e!=nil{return nil,e};out:=make([]SemanticChart,0,n);var prev wire.Ref;for i:=uint64(0);i<n;i++{cr,e:=c.ref();if e!=nil{return nil,e};if i>0&&!refLess(prev,cr){return nil,&Error{"CHART_ORDER"}};prev=cr;ct,e:=c.ref();if e!=nil{return nil,e};ver,e:=c.u();if e!=nil{return nil,e};dom,e:=c.ref();if e!=nil{return nil,e};cs,e:=c.ref();if e!=nil{return nil,e};p,e:=c.ref();if e!=nil{return nil,e};a,e:=c.ref();if e!=nil{return nil,e};prov,e:=c.ref();if e!=nil{return nil,e};flags,e:=c.u();if e!=nil{return nil,e};out=append(out,SemanticChart{cr,ct,ver,dom,cs,p,a,prov,flags})};if e:=c.done();e!=nil{return nil,e};return out,nil}
func boolFlag(v uint64)(bool,error){if v>1{return false,&Error{"BOOL_FLAG_INVALID"}};return v==1,nil}
func DecodeTransitions(d []byte)([]Transition,error){c:=cur{d:d};n,e:=c.u();if e!=nil{return nil,e};out:=make([]Transition,0,n);var prev wire.Ref;for i:=uint64(0);i<n;i++{tr,e:=c.ref();if e!=nil{return nil,e};if i>0&&!refLess(prev,tr){return nil,&Error{"TRANSITION_ORDER"}};prev=tr;s,e:=c.ref();if e!=nil{return nil,e};t,e:=c.ref();if e!=nil{return nil,e};tf,e:=c.ref();if e!=nil{return nil,e};f,e:=c.u();if e!=nil{return nil,e};if f>4{return nil,&Error{"TRANSITION_FIDELITY_INVALID"}};dv,e:=c.u();if e!=nil{return nil,e};det,e:=boolFlag(dv);if e!=nil{return nil,e};rv,e:=c.u();if e!=nil{return nil,e};rev,e:=boolFlag(rv);if e!=nil{return nil,e};bound,e:=c.ref();if e!=nil{return nil,e};preserved,e:=refs(&c);if e!=nil{return nil,e};lost,e:=refs(&c);if e!=nil{return nil,e};seen:=map[wire.Ref]bool{};for _,r:=range preserved{seen[r]=true};for _,r:=range lost{if seen[r]{return nil,&Error{"TRANSITION_INVARIANT_OVERLAP"}}};val,e:=c.ref();if e!=nil{return nil,e};auth,e:=c.ref();if e!=nil{return nil,e};prov,e:=c.ref();if e!=nil{return nil,e};out=append(out,Transition{tr,s,t,tf,f,det,rev,bound,preserved,lost,val,auth,prov})};if e:=c.done();e!=nil{return nil,e};return out,nil}
func DecodeOperators(d []byte)([]Operator,error){c:=cur{d:d};n,e:=c.u();if e!=nil{return nil,e};out:=make([]Operator,0,n);var prev wire.Ref;for i:=uint64(0);i<n;i++{op,e:=c.ref();if e!=nil{return nil,e};if i>0&&!refLess(prev,op){return nil,&Error{"OPERATOR_ORDER"}};prev=op;dom,e:=c.ref();if e!=nil{return nil,e};cod,e:=c.ref();if e!=nil{return nil,e};sig,e:=c.ref();if e!=nil{return nil,e};guard,e:=c.ref();if e!=nil{return nil,e};caps,e:=refs(&c);if e!=nil{return nil,e};effects,e:=refs(&c);if e!=nil{return nil,e};auths,e:=refs(&c);if e!=nil{return nil,e};inv,e:=refs(&c);if e!=nil{return nil,e};present,e:=c.u();if e!=nil{return nil,e};if present>1{return nil,&Error{"OPERATOR_EXECUTOR_FLAG_INVALID"}};var ex *wire.Ref;if present==1{r,e:=c.ref();if e!=nil{return nil,e};ex=&r};bound,e:=c.ref();if e!=nil{return nil,e};prov,e:=c.ref();if e!=nil{return nil,e};out=append(out,Operator{op,dom,cod,sig,guard,caps,effects,auths,inv,ex,bound,prov})};if e:=c.done();e!=nil{return nil,e};return out,nil}
func DecodeAuthorities(d []byte)([]AuthorityRecord,error){c:=cur{d:d};n,e:=c.u();if e!=nil{return nil,e};out:=make([]AuthorityRecord,0,n);var prev wire.Ref;for i:=uint64(0);i<n;i++{ar,e:=c.ref();if e!=nil{return nil,e};if i>0&&!refLess(prev,ar){return nil,&Error{"AUTHORITY_ORDER"}};prev=ar;subj,e:=c.ref();if e!=nil{return nil,e};issuer,e:=c.ref();if e!=nil{return nil,e};grants,e:=refs(&c);if e!=nil{return nil,e};denies,e:=refs(&c);if e!=nil{return nil,e};scope,e:=c.ref();if e!=nil{return nil,e};mask,e:=c.u();if e!=nil{return nil,e};if mask&^uint64(7)!=0{return nil,&Error{"AUTHORITY_OPTION_MASK_INVALID"}};var validity,evidence,signature *wire.Ref;if mask&1!=0{r,e:=c.ref();if e!=nil{return nil,e};validity=&r};if mask&2!=0{r,e:=c.ref();if e!=nil{return nil,e};evidence=&r};if mask&4!=0{r,e:=c.ref();if e!=nil{return nil,e};signature=&r};out=append(out,AuthorityRecord{ar,subj,issuer,grants,denies,scope,validity,evidence,signature})};if e:=c.done();e!=nil{return nil,e};return out,nil}
