package conformance

import (
    "crypto/sha256"
    "fmt"
    "strings"
    "github.com/kakon77777-commits/isql-origin-go/sections"
    "github.com/kakon77777-commits/isql-origin-go/wire"
)
type Native struct{ Profile string; Kind string; Version uint64; ProfileRef,KindRef,CodecRef wire.Ref }
func DetectNative(data []byte)(Native,error){if len(data)>=5{s:=string(data[:4]);v:=uint64(data[4]);switch s{case "ISN7":if v!=7{return Native{},fmt.Errorf("PROFILE_NATIVE_VERSION_UNSUPPORTED")};return Native{"isql-mem","mem.isn7",v,wire.Ref{0,10},wire.Ref{0,20},wire.Ref{0,50}},nil;case "ISD8":if v!=8{return Native{},fmt.Errorf("PROFILE_NATIVE_VERSION_UNSUPPORTED")};return Native{"isql-mem","mem.isd8",v,wire.Ref{0,10},wire.Ref{0,21},wire.Ref{0,51}},nil;case "ILI1":if v!=1{return Native{},fmt.Errorf("PROFILE_NATIVE_VERSION_UNSUPPORTED")};return Native{"isql-mem","mem.ili1",v,wire.Ref{0,10},wire.Ref{0,22},wire.Ref{0,52}},nil}};if len(data)>=4&&data[0]==0xd5&&data[1]==0x51{switch data[2]{case 0xb1:if data[3]!=4{return Native{},fmt.Errorf("PROFILE_NATIVE_VERSION_UNSUPPORTED")};return Native{"isql-dsr","dsr.registry",4,wire.Ref{0,11},wire.Ref{0,30},wire.Ref{0,53}},nil;case 0xc1:if data[3]!=5{return Native{},fmt.Errorf("PROFILE_NATIVE_VERSION_UNSUPPORTED")};return Native{"isql-dsr","dsr.state",5,wire.Ref{0,11},wire.Ref{0,31},wire.Ref{0,54}},nil;case 0xe1:if data[3]==5{return Native{"isql-dsr","dsr.event-stream",5,wire.Ref{0,11},wire.Ref{0,32},wire.Ref{0,55}},nil};if data[3]==6{return Native{"isql-dsr","dsr.causal-program",6,wire.Ref{0,11},wire.Ref{0,34},wire.Ref{0,57}},nil};case 0xb7:if data[3]!=6{return Native{},fmt.Errorf("PROFILE_NATIVE_VERSION_UNSUPPORTED")};return Native{"isql-dsr","dsr.branch",6,wire.Ref{0,11},wire.Ref{0,33},wire.Ref{0,56}},nil;case 0xe2:if data[3]<7||data[3]>10{return Native{},fmt.Errorf("PROFILE_NATIVE_VERSION_UNSUPPORTED")};return Native{"isql-dsr","dsr.vm-program",uint64(data[3]),wire.Ref{0,11},wire.Ref{0,35},wire.Ref{0,58}},nil}};return Native{},fmt.Errorf("PROFILE_NATIVE_UNRECOGNIZED")}
func sectionMap(obj wire.OMIR)map[uint64][]byte{m:=map[uint64][]byte{};for _,s:=range obj.Sections{m[s.Tag]=s.Payload};return m}
func ValidateObject(obj wire.OMIR,registries map[uint64][]byte)[]string{errs:=[]string{};for _,pin:=range obj.RegistryPins{raw,ok:=registries[pin.Slot];if !ok{errs=append(errs,fmt.Sprintf("REGISTRY_SLOT_MISSING:%d",pin.Slot));continue};orb,e:=wire.DecodeORB(raw);if e!=nil{errs=append(errs,"REGISTRY_DECODE_FAILED");continue};if orb.BundleKind!=pin.RegistryKind{errs=append(errs,"REGISTRY_KIND_MISMATCH")};if orb.Revision!=pin.Revision{errs=append(errs,"REGISTRY_REVISION_MISMATCH")};h:=sha256.Sum256(raw);if string(h[:])!=string(pin.Digest.Bytes){errs=append(errs,"REGISTRY_DIGEST_MISMATCH")}};by:=sectionMap(obj);if p,ok:=by[1];ok{if _,e:=sections.DecodeIdentityFamily(p);e!=nil{errs=append(errs,"P0_SECTION_DECODE_FAILED:1")}};if p,ok:=by[8];ok{if _,e:=sections.DecodeInvariantContracts(p);e!=nil{errs=append(errs,"P0_SECTION_DECODE_FAILED:8")}};if p,ok:=by[9];ok{if _,e:=sections.DecodePayloadTable(p);e!=nil{errs=append(errs,"P0_SECTION_DECODE_FAILED:9")}};if p,ok:=by[10];ok{pb,e:=sections.DecodeProfileBinding(p);if e!=nil{errs=append(errs,"P0_SECTION_DECODE_FAILED:10")}else{for _,tag:=range pb.RequiredSections{if _,ok:=by[tag];!ok{errs=append(errs,fmt.Sprintf("PROFILE_REQUIRED_SECTION_MISSING:%d",tag))}};if pb.Profile!=obj.Profile{errs=append(errs,"PROFILE_HEADER_BINDING_MISMATCH")}}};return errs}
func ValidateP1Wrapper(obj wire.OMIR,registries map[uint64][]byte)[]string{errs:=ValidateObject(obj,registries);by:=sectionMap(obj);if len(obj.Sections)!=4||obj.Sections[0].Tag!=1||obj.Sections[1].Tag!=8||obj.Sections[2].Tag!=9||obj.Sections[3].Tag!=10{return append(errs,"P1_SECTION_SET_INVALID")};ids,e1:=sections.DecodeIdentityFamily(by[1]);_,e2:=sections.DecodeInvariantContracts(by[8]);payloads,e3:=sections.DecodePayloadTable(by[9]);pb,e4:=sections.DecodeProfileBinding(by[10]);if e1!=nil||e2!=nil||e3!=nil||e4!=nil{return append(errs,"P1_SECTION_DECODE_FAILED")};if len(payloads)!=1{return append(errs,"P1_NATIVE_PAYLOAD_CARDINALITY_INVALID")};p:=payloads[0];raw:=p.Body;h:=sha256.Sum256(raw);if string(p.Digest.Bytes)!=string(h[:]){errs=append(errs,"P1_NATIVE_PAYLOAD_DIGEST_MISMATCH")};if len(ids)!=1||string(ids[0].Digest)!=string(h[:]){errs=append(errs,"P1_NATIVE_IDENTITY_MISMATCH")};det,e:=DetectNative(raw);if e!=nil{return append(errs,"P1_NATIVE_DETECTION_FAILED:"+e.Error())};if obj.Profile!=det.ProfileRef{errs=append(errs,"P1_NATIVE_PROFILE_MISMATCH")};if obj.ObjectKind!=det.KindRef{errs=append(errs,"P1_NATIVE_OBJECT_KIND_MISMATCH")};if p.Codec!=det.CodecRef{errs=append(errs,"P1_NATIVE_CODEC_MISMATCH")};if pb.Profile!=det.ProfileRef||len(pb.ObjectKinds)!=1||pb.ObjectKinds[0]!=det.KindRef{errs=append(errs,"P1_PROFILE_BINDING_MISMATCH")};out:=[]string{};seen:=map[string]bool{};for _,x:=range errs{if !seen[x]{seen[x]=true;out=append(out,x)}};return out}
func HasError(errs []string,substr string)bool{return strings.Contains(strings.Join(errs,"|"),substr)}
