package conformance

import (
    "encoding/json"
    "fmt"
    "os"
    "path/filepath"
    "strconv"
    "strings"
    "github.com/kakon77777-commits/isql-origin-go/sidecar"
    "github.com/kakon77777-commits/isql-origin-go/wire"
)
type CaseResult struct{Suite string `json:"suite"`;Name string `json:"name"`;Status string `json:"status"`;Detail string `json:"detail,omitempty"`};type Report struct{Schema string `json:"schema"`;Implementation string `json:"implementation"`;GoVersion string `json:"go_version,omitempty"`;Total int `json:"total"`;Passed int `json:"passed"`;Failures int `json:"failures"`;SpecGaps int `json:"spec_gaps"`;Cases []CaseResult `json:"cases"`}
func readRoot(root string,parts ...string)([]byte,error){return os.ReadFile(filepath.Join(append([]string{root},parts...)...))};func add(r *Report,suite,name,status,detail string){r.Total++;switch status{case "PASS":r.Passed++;case "SPEC_GAP":r.SpecGaps++;default:r.Failures++};r.Cases=append(r.Cases,CaseResult{suite,name,status,detail})};func matchesErr(got []string,want string)bool{return want==""||strings.Contains(strings.Join(got,"|"),want)};func errContains(err error,want string)bool{return err!=nil&&(want==""||strings.Contains(err.Error(),want))};func parseRefCSV(s string)([]wire.Ref,error){if s==""{return nil,nil};parts:=strings.Split(s,",");out:=make([]wire.Ref,0,len(parts));for _,p:=range parts{r,e:=parseRef(strings.TrimSpace(p));if e!=nil{return nil,e};out=append(out,r)};return out,nil}
func runP0(root string,r *Report){type row struct{Name,Kind,File,Expectation,ErrorContains string;Registries map[string]string `json:"registries"`};var m struct{Cases []row `json:"cases"`};b,e:=readRoot(root,"vectors","manifest.json");if e!=nil{add(r,"p0","manifest","FAIL",e.Error());return};if e=json.Unmarshal(b,&m);e!=nil{add(r,"p0","manifest","FAIL",e.Error());return};for _,c:=range m.Cases{switch c.Kind{case "orb":raw,_:=readRoot(root,"vectors",c.File);_,err:=wire.DecodeORB(raw);ok:=(c.Expectation=="decode-pass"&&err==nil)||(c.Expectation=="decode-fail"&&errContains(err,c.ErrorContains));if ok{add(r,"p0",c.Name,"PASS","")}else{add(r,"p0",c.Name,"FAIL",fmt.Sprintf("err=%v",err))};case "omir":raw,_:=readRoot(root,"vectors",c.File);obj,err:=wire.DecodeOMIR(raw);if c.Expectation=="decode-fail"{if errContains(err,c.ErrorContains){add(r,"p0",c.Name,"PASS","")}else{add(r,"p0",c.Name,"FAIL",fmt.Sprintf("err=%v",err))};continue};if err!=nil{add(r,"p0",c.Name,"FAIL",err.Error());continue};if c.Expectation=="decode-pass"{add(r,"p0",c.Name,"PASS","");continue};regs:=map[uint64][]byte{};for k,v:=range c.Registries{slot,_:=strconv.ParseUint(k,10,64);rr,_:=readRoot(root,"vectors",v);regs[slot]=rr};errs:=ValidateObject(obj,regs);if c.Expectation=="object-validation-pass"&&len(errs)==0{add(r,"p0",c.Name,"PASS","")}else if c.Expectation=="object-validation-fail"&&matchesErr(errs,c.ErrorContains){add(r,"p0",c.Name,"PASS","")}else{add(r,"p0",c.Name,"FAIL",strings.Join(errs,"|"))}}}}
func runP1(root string,r *Report){type row struct{Name,File,Gate string;ExpectedExit int `json:"expected_exit"`;ErrorContains string `json:"error_contains"`};var m struct{Cases []row `json:"cases"`};b,_:=readRoot(root,"vectors","p1","manifest.json");if e:=json.Unmarshal(b,&m);e!=nil{add(r,"p1","manifest","FAIL",e.Error());return};reg,_:=readRoot(root,"examples","p1","profile-registry.orb");for _,c:=range m.Cases{raw,_:=readRoot(root,"vectors","p1",c.File);switch c.Gate{case "validate-wrapper":obj,e:=wire.DecodeOMIR(raw);if e!=nil{add(r,"p1",c.Name,"FAIL",e.Error());continue};errs:=ValidateP1Wrapper(obj,map[uint64][]byte{0:reg});if c.ExpectedExit==0&&len(errs)==0{add(r,"p1",c.Name,"PASS","")}else if c.ExpectedExit!=0&&matchesErr(errs,c.ErrorContains){add(r,"p1",c.Name,"PASS","")}else{add(r,"p1",c.Name,"FAIL",strings.Join(errs,"|"))};case "profile-detect":_,e:=DetectNative(raw);if c.ExpectedExit==0&&e==nil{add(r,"p1",c.Name,"PASS","")}else if c.ExpectedExit!=0&&errContains(e,c.ErrorContains){add(r,"p1",c.Name,"PASS","")}else{add(r,"p1",c.Name,"FAIL",fmt.Sprintf("err=%v",e))}}}}
func runP2(root string,r *Report){type vr struct{Name,File string;ExpectedExit int `json:"expected_exit"`;ErrorContains string `json:"error_contains"`};type hr struct{Name,File,Harness,Payload,Path,Invariant string;ExpectedExit int `json:"expected_exit"`;ExpectedStatus string `json:"expected_status"`};var m struct{Validation []vr `json:"validation_cases"`;Holonomy []hr `json:"holonomy_cases"`};b,_:=readRoot(root,"vectors","p2","manifest.json");if e:=json.Unmarshal(b,&m);e!=nil{add(r,"p2","manifest","FAIL",e.Error());return};for _,c:=range m.Validation{raw,_:=readRoot(root,"vectors","p2",c.File);obj,e:=wire.DecodeOMIR(raw);if e!=nil{add(r,"p2",c.Name,"FAIL",e.Error());continue};errs:=ValidateP23(obj);if c.ExpectedExit==0&&len(errs)==0{add(r,"p2",c.Name,"PASS","")}else if c.ExpectedExit!=0&&matchesErr(errs,c.ErrorContains){add(r,"p2",c.Name,"PASS","")}else{add(r,"p2",c.Name,"FAIL",strings.Join(errs,"|"))}};for _,c:=range m.Holonomy{raw,_:=readRoot(root,"vectors","p2",c.File);obj,e:=wire.DecodeOMIR(raw);if e!=nil{add(r,"p2",c.Name,"FAIL",e.Error());continue};h,_:=readRoot(root,"vectors","p2",c.Harness);p,_:=readRoot(root,"vectors","p2",c.Payload);pathRefs,e:=parseRefCSV(c.Path);if e!=nil{add(r,"p2",c.Name,"FAIL",e.Error());continue};inv,e:=parseRef(c.Invariant);if e!=nil{add(r,"p2",c.Name,"FAIL",e.Error());continue};rep,e:=RunHolonomy(obj,h,p,pathRefs,inv);if c.ExpectedExit==0&&e==nil&&rep.Status==c.ExpectedStatus{add(r,"p2",c.Name,"PASS","")}else{add(r,"p2",c.Name,"FAIL",fmt.Sprintf("status=%s err=%v",rep.Status,e))}}}
func runP3(root string,r *Report){type vr struct{Name,File string;ExpectedExit int `json:"expected_exit"`;ErrorContains string `json:"error_contains"`};type cr struct{Name,File,Operator,Context string;ExpectedExit int `json:"expected_exit"`;ExpectedReady bool `json:"expected_ready"`};type hr struct{Name,File,Operator,Context,Executor string;ExpectedExit int `json:"expected_exit"`;ErrorContains string `json:"error_contains"`};var m struct{Validation []vr `json:"validation_cases"`;Certificates []cr `json:"certificate_cases"`;Handoffs []hr `json:"handoff_cases"`};b,_:=readRoot(root,"vectors","p3","manifest.json");if e:=json.Unmarshal(b,&m);e!=nil{add(r,"p3","manifest","FAIL",e.Error());return};for _,c:=range m.Validation{raw,_:=readRoot(root,"vectors","p3",c.File);obj,e:=wire.DecodeOMIR(raw);if e!=nil{add(r,"p3",c.Name,"FAIL",e.Error());continue};errs:=ValidateP23(obj);if c.ExpectedExit==0&&len(errs)==0{add(r,"p3",c.Name,"PASS","")}else if c.ExpectedExit!=0&&matchesErr(errs,c.ErrorContains){add(r,"p3",c.Name,"PASS","")}else{add(r,"p3",c.Name,"FAIL",strings.Join(errs,"|"))}};for _,c:=range m.Certificates{raw,_:=readRoot(root,"vectors","p3",c.File);obj,_:=wire.DecodeOMIR(raw);op,_:=parseRef(c.Operator);ctx,_:=readRoot(root,"vectors","p3",c.Context);cert,e:=BuildActionCertificate(raw,obj,op,ctx);if e==nil&&cert.Ready==c.ExpectedReady{add(r,"p3",c.Name,"PASS","")}else{add(r,"p3",c.Name,"FAIL",fmt.Sprintf("ready=%v err=%v",cert.Ready,e))}};for _,c:=range m.Handoffs{raw,_:=readRoot(root,"vectors","p3",c.File);obj,_:=wire.DecodeOMIR(raw);op,_:=parseRef(c.Operator);ctx,_:=readRoot(root,"vectors","p3",c.Context);cert,e:=BuildActionCertificate(raw,obj,op,ctx);if e!=nil{add(r,"p3",c.Name,"FAIL",e.Error());continue};exe,_:=readRoot(root,c.Executor);_,e=PrepareDSRHandoff(cert,exe);if c.ExpectedExit==0&&e==nil{add(r,"p3",c.Name,"PASS","")}else if c.ExpectedExit!=0&&errContains(e,c.ErrorContains){add(r,"p3",c.Name,"PASS","")}else{add(r,"p3",c.Name,"FAIL",fmt.Sprintf("err=%v",e))}}}
func runP4(root string,r *Report){type row struct{Name,Command,Source,Target,Plan,Observations string;ExpectedExit int `json:"expected_exit"`;ExpectedStatus string `json:"expected_status"`;ErrorContains string `json:"error_contains"`};var m struct{Cases []row `json:"bridge_cases"`};b,_:=readRoot(root,"vectors","p4","manifest.json");if e:=json.Unmarshal(b,&m);e!=nil{add(r,"p4","manifest","FAIL",e.Error());return};for _,c:=range m.Cases{src,_:=readRoot(root,c.Source);tgt,_:=readRoot(root,c.Target);pb,_:=readRoot(root,c.Plan);plan,e:=sidecar.ParseBridgePlan(pb);if e!=nil{add(r,"p4",c.Name,"FAIL",e.Error());continue};if c.Command=="bridge-candidate"{cand,e:=sidecar.BuildBridgeCandidate(src,tgt,plan);if e==nil&&cand.Status==c.ExpectedStatus{add(r,"p4",c.Name,"PASS","")}else{add(r,"p4",c.Name,"FAIL",fmt.Sprintf("status=%s err=%v",cand.Status,e))};continue};obs,_:=readRoot(root,c.Observations);rec,e:=sidecar.VerifyBridge(src,tgt,plan,obs);if c.ExpectedExit<=1&&e==nil&&rec.Status==c.ExpectedStatus{add(r,"p4",c.Name,"PASS","")}else if c.ExpectedExit==2&&errContains(e,c.ErrorContains){add(r,"p4",c.Name,"PASS","")}else{add(r,"p4",c.Name,"FAIL",fmt.Sprintf("status=%s err=%v",rec.Status,e))}}}
func runP5(root string,r *Report){type row struct{Name,Command,File,Source,Target,Plan,Observations string;ExpectedExit int `json:"expected_exit"`;ExpectedProfile string `json:"expected_profile"`;ExpectedStatus string `json:"expected_status"`;ErrorContains string `json:"error_contains"`};var m struct{Cases []row `json:"cases"`};b,_:=readRoot(root,"vectors","p5","manifest.json");if e:=json.Unmarshal(b,&m);e!=nil{add(r,"p5","manifest","FAIL",e.Error());return};for _,c:=range m.Cases{switch c.Command{case "mlf-info":raw,_:=readRoot(root,c.File);info,e:=sidecar.InspectMLF(raw);if c.ExpectedExit==0&&e==nil&&info.Profile==c.ExpectedProfile{add(r,"p5",c.Name,"PASS","")}else if c.ExpectedExit!=0&&errContains(e,c.ErrorContains){add(r,"p5",c.Name,"PASS","")}else{add(r,"p5",c.Name,"FAIL",fmt.Sprintf("profile=%s err=%v",info.Profile,e))};case "wrap-native":add(r,"p5",c.Name,"SPEC_GAP","P5 extension Registry numeric assignment is not normative in published specs");case "bridge-verify":src,_:=readRoot(root,c.Source);tgt,_:=readRoot(root,c.Target);pb,_:=readRoot(root,c.Plan);plan,e:=sidecar.ParseBridgePlan(pb);if e!=nil{add(r,"p5",c.Name,"FAIL",e.Error());continue};obs,_:=readRoot(root,c.Observations);rec,e:=sidecar.VerifyBridge(src,tgt,plan,obs);if c.ExpectedExit<=1&&e==nil&&rec.Status==c.ExpectedStatus{add(r,"p5",c.Name,"PASS","")}else if c.ExpectedExit==2&&errContains(e,c.ErrorContains){add(r,"p5",c.Name,"PASS","")}else{add(r,"p5",c.Name,"FAIL",fmt.Sprintf("status=%s err=%v",rec.Status,e))}}}}
func RunAll(root string)Report{r:=Report{Schema:"isql-origin-independent-conformance/v0.7",Implementation:"go-stdlib-independent"};runP0(root,&r);runP1(root,&r);runP2(root,&r);runP3(root,&r);runP4(root,&r);runP5(root,&r);return r}
